#ifndef INCLUDED
#define INCLUDED

UNITY_INSTANCING_BUFFER_START(BulletProperties)
	UNITY_DEFINE_INSTANCED_PROP(float4, Positions)
	UNITY_DEFINE_INSTANCED_PROP(float, Radiuses)
	UNITY_DEFINE_INSTANCED_PROP(float4, Directions)
UNITY_INSTANCING_BUFFER_END(bulletProps)

struct vIn
{

	float4 vertex : POSITION;
	float2 uv : TEXCOORD0;

	UNITY_VERTEX_INPUT_INSTANCE_ID

};

#endif